title: Vitaliy Beletskiy
logo: "/images/profile_image.png?raw=true"
description: >
 <b>Skills:</b><br>
 - Android (Kotlin), iOS (Swift)<br>
 - Agile (Scrum, Kanban)<br>
 - git (GitHub, Azure DevOps)<br>
  <br>
  <b>Experience  with:</b><br>
  - ะก#, ASP.NET, HTML/CSS, PHP, C, VBA<br>
  - MS SQL Server, MySQL, Firebase<br>
 <br>
 <br>
 <a href="https://www.linkedin.com/in/vitaliy-beletskiy">View My LinkedIn Profile</a> 
 <a href="https://github.com/VitaliyBeletskiy">View My GitHub Profile</a>

theme: jekyll-theme-minimal
